In [1]:
import json
import pandas as pd

tweets_data = []
# Open connection to file
h=open('data/output/sauditweets.txt','r')

# Read in tweets and store in list: tweets_data
for i in h:
    try:
        tmp=json.loads(i)
        tweets_data.append(tmp)
    except:
        print('X'), #shows lines with errors
h.close()

In [3]:
df = pd.DataFrame(tweets_data)
df

,created_at,id,id_str,text,source,truncated,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,...,lang,timestamp_ms,display_text_range,extended_entities,possibly_sensitive,extended_tweet,quoted_status_id,quoted_status_id_str,quoted_status,quoted_status_permalink
0,Tue Sep 29 14:49:06 +0000 2020,1310954762666487810,1310954762666487810,راح العود اللي خالي من العذاريب \nاللي يمناه م...,"<a href=""http://twitter.com/download/iphone"" r...",False,NaN,None,NaN,None,...,ar,1601390946438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tue Sep 29 14:49:07 +0000 2020,1310954767032766465,1310954767032766465,#الشيخ_صباح_الاحمد_الصباح https://t.co/nAF4xDL5a4,"<a href=""http://twitter.com/download/iphone"" r...",False,NaN,None,NaN,None,...,und,1601390947479,"[0, 25]","{'media': [{'id': 1310954760749678597, 'id_str...",False,NaN,NaN,NaN,NaN,NaN
2,Tue Sep 29 14:49:07 +0000 2020,1310954768693628929,1310954768693628929,انا لله وأنا اليه راجعون ، نعزي انفسنا ونعزي ا...,"<a href=""http://twitter.com/download/iphone"" r...",True,NaN,None,NaN,None,...,ar,1601390947875,NaN,NaN,NaN,{'full_text': 'انا لله وأنا اليه راجعون ، نعزي...,NaN,NaN,NaN,NaN
3,Tue Sep 29 14:49:08 +0000 2020,1310954769255731205,1310954769255731205,@Rokkaya89 عبالك تاتو رباني شبي حظي 😭,"<a href=""http://twitter.com/download/iphone"" r...",False,1.310955e+18,1310954638380761090,2.363014e+09,2363014047,...,ar,1601390948009,"[11, 37]",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Tue Sep 29 14:49:07 +0000 2020,1310954769196945413,1310954769196945413,"وها قد غابت شمس الكويت , \nاللهم أجرنا في مصيب...","<a href=""http://twitter.com/download/iphone"" r...",True,NaN,None,NaN,None,...,ar,1601390947995,"[0, 140]",NaN,False,"{'full_text': 'وها قد غابت شمس الكويت , اللهم...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99993,Wed Sep 30 09:42:57 +0000 2020,1311240107593281536,1311240107593281536,كنت أتساءل \nلماذا يختار الموت أفضل من فينا؟ \...,"<a href=""http://twitter.com/download/iphone"" r...",False,NaN,None,NaN,None,...,ar,1601458977970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99994,Wed Sep 30 09:42:58 +0000 2020,1311240108331470848,1311240108331470848,@becktalia הגזמת,"<a href=""http://twitter.com/download/iphone"" r...",False,1.311240e+18,1311239747797487617,2.701762e+09,2701761817,...,iw,1601458978146,"[11, 16]",NaN,NaN,NaN,NaN,NaN,NaN,NaN
99995,Wed Sep 30 09:42:58 +0000 2020,1311240111024148481,1311240111024148481,@i7arth @LxRY_7 @Count__Vampire مسكين خلود ساك...,"<a href=""http://twitter.com/download/iphone"" r...",False,1.311240e+18,1311239939934351360,1.082444e+09,1082444168,...,ar,1601458978788,"[32, 60]",NaN,NaN,NaN,NaN,NaN,NaN,NaN
99996,Wed Sep 30 09:42:59 +0000 2020,1311240113389789184,1311240113389789184,من الطبيعي أن نختلف ونعتذر .. \nونعاتب .. \nو...,"<a href=""http://tapbots.com/tweetbot"" rel=""nof...",True,NaN,None,NaN,None,...,ar,1601458979352,NaN,NaN,NaN,{'full_text': 'من الطبيعي أن نختلف ونعتذر .. ...,NaN,NaN,NaN,NaN
99997,Wed Sep 30 09:43:00 +0000 2020,1311240116271222785,1311240116271222785,@maiconroque27 💪🏻 https://t.co/23MmIpb7R2,"<a href=""http://twitter.com/download/iphone"" r...",False,NaN,None,4.144883e+09,4144883333,...,und,1601458980039,"[0, 17]","{'media': [{'id': 1311239974000394241, 'id_str...",False,NaN,NaN,NaN,NaN,NaN

In [4]:
places = df['place'].apply(pd.Series)
places

,id,url,place_type,name,full_name,country_code,country,bounding_box,attributes
0,01bf5c1e56ac186d,https://api.twitter.com/1.1/geo/id/01bf5c1e56a...,city,الرياض,"الرياض, المملكة العربية السعودية",SA,المملكة العربية السعودية,"{'type': 'Polygon', 'coordinates': [[[46.30439...",{}
1,000799c66e428a87,https://api.twitter.com/1.1/geo/id/000799c66e4...,city,Jeddah,"Jeddah, Kingdom of Saudi Arabia",SA,Kingdom of Saudi Arabia,"{'type': 'Polygon', 'coordinates': [[[38.92965...",{}
2,0033b59d59056043,https://api.twitter.com/1.1/geo/id/0033b59d590...,admin,Al Rayyan,"Al Rayyan, Qatar",QA,Qatar,"{'type': 'Polygon', 'coordinates': [[[50.75007...",{}
3,b62cd77425868341,https://api.twitter.com/1.1/geo/id/b62cd774258...,country,Iraq,Iraq,IQ,Iraq,"{'type': 'Polygon', 'coordinates': [[[38.79470...",{}
4,01609a675eba6f1d,https://api.twitter.com/1.1/geo/id/01609a675eb...,city,Al Surra,"Al Surra, Kuwait",KW,Kuwait,"{'type': 'Polygon', 'coordinates': [[[47.99377...",{}
...,...,...,...,...,...,...,...,...,...
99993,e3e9c55876b99760,https://api.twitter.com/1.1/geo/id/e3e9c55876b...,country,مملكة البحرين,مملكة البحرين,BH,مملكة البحرين,"{'type': 'Polygon', 'coordinates': [[[50.32511...",{}
99994,2edb6e240797c549,https://api.twitter.com/1.1/geo/id/2edb6e24079...,country,Israel,Israel,IL,Israel,"{'type': 'Polygon', 'coordinates': [[[34.26692...",{}
99995,001907e868d06e24,https://api.twitter.com/1.1/geo/id/001907e868d...,admin,Dubai,"Dubai, United Arab Emirates",AE,United Arab Emirates,"{'type': 'Polygon', 'coordinates': [[[54.89397...",{}
99996,017189e6700ad6cd,https://api.twitter.com/1.1/geo/id/017189e6700...,city,الاحساء,"الاحساء, المملكة العربية السعودية",SA,المملكة العربية السعودية,"{'type': 'Polygon', 'coordinates': [[[49.41665...",{}
99997,01fc978d41e183e7,https://api.twitter.com/1.1/geo/id/01fc978d41e...,admin,جازان,"جازان, المملكة العربية السعودية",SA,المملكة العربية السعودية,"{'type': 'Polygon', 'coordinates': [[[41.75298...",{}

In [5]:
places = places.rename(columns = lambda x : 'place_' + str(x))
places

,place_id,place_url,place_place_type,place_name,place_full_name,place_country_code,place_country,place_bounding_box,place_attributes
0,01bf5c1e56ac186d,https://api.twitter.com/1.1/geo/id/01bf5c1e56a...,city,الرياض,"الرياض, المملكة العربية السعودية",SA,المملكة العربية السعودية,"{'type': 'Polygon', 'coordinates': [[[46.30439...",{}
1,000799c66e428a87,https://api.twitter.com/1.1/geo/id/000799c66e4...,city,Jeddah,"Jeddah, Kingdom of Saudi Arabia",SA,Kingdom of Saudi Arabia,"{'type': 'Polygon', 'coordinates': [[[38.92965...",{}
2,0033b59d59056043,https://api.twitter.com/1.1/geo/id/0033b59d590...,admin,Al Rayyan,"Al Rayyan, Qatar",QA,Qatar,"{'type': 'Polygon', 'coordinates': [[[50.75007...",{}
3,b62cd77425868341,https://api.twitter.com/1.1/geo/id/b62cd774258...,country,Iraq,Iraq,IQ,Iraq,"{'type': 'Polygon', 'coordinates': [[[38.79470...",{}
4,01609a675eba6f1d,https://api.twitter.com/1.1/geo/id/01609a675eb...,city,Al Surra,"Al Surra, Kuwait",KW,Kuwait,"{'type': 'Polygon', 'coordinates': [[[47.99377...",{}
...,...,...,...,...,...,...,...,...,...
99993,e3e9c55876b99760,https://api.twitter.com/1.1/geo/id/e3e9c55876b...,country,مملكة البحرين,مملكة البحرين,BH,مملكة البحرين,"{'type': 'Polygon', 'coordinates': [[[50.32511...",{}
99994,2edb6e240797c549,https://api.twitter.com/1.1/geo/id/2edb6e24079...,country,Israel,Israel,IL,Israel,"{'type': 'Polygon', 'coordinates': [[[34.26692...",{}
99995,001907e868d06e24,https://api.twitter.com/1.1/geo/id/001907e868d...,admin,Dubai,"Dubai, United Arab Emirates",AE,United Arab Emirates,"{'type': 'Polygon', 'coordinates': [[[54.89397...",{}
99996,017189e6700ad6cd,https://api.twitter.com/1.1/geo/id/017189e6700...,city,الاحساء,"الاحساء, المملكة العربية السعودية",SA,المملكة العربية السعودية,"{'type': 'Polygon', 'coordinates': [[[49.41665...",{}
99997,01fc978d41e183e7,https://api.twitter.com/1.1/geo/id/01fc978d41e...,admin,جازان,"جازان, المملكة العربية السعودية",SA,المملكة العربية السعودية,"{'type': 'Polygon', 'coordinates': [[[41.75298...",{}

In [6]:
df = pd.concat([df[:], places[:]], axis=1)

In [7]:
users = df['user'].apply(pd.Series)
users = users.rename(columns = lambda x : 'user_' + str(x))
users

,user_id,user_id_str,user_name,user_screen_name,user_location,user_url,user_description,user_translator_type,user_protected,user_verified,...,user_profile_text_color,user_profile_use_background_image,user_profile_image_url,user_profile_image_url_https,user_profile_banner_url,user_default_profile,user_default_profile_image,user_following,user_follow_request_sent,user_notifications
0,2473097725,2473097725,عايض صالح بن سمره💙,a_s__alrashidi,🇰🇼🇸🇦,None,-DENTAL STUDENT - لست وحيداً بل الله معي. -♥️٩...,none,False,False,...,333333,True,http://pbs.twimg.com/profile_images/1301699140...,https://pbs.twimg.com/profile_images/130169914...,https://pbs.twimg.com/profile_banners/24730977...,True,False,None,None,None
1,442127734,442127734,Badawi D Kaloti 🇸🇦🇵🇸,BadawiKaloti,jeddah,None,"Jeddah KSA , ALAHLI-FC",none,False,False,...,333333,True,http://pbs.twimg.com/profile_images/1241713944...,https://pbs.twimg.com/profile_images/124171394...,https://pbs.twimg.com/profile_banners/44212773...,True,False,None,None,None
2,474134674,474134674,زامل بن سياف الشهراني,Zamel56,الدوحة قطر,None,اللهم ارزقنا القبول وحسن الخاتمة,none,False,False,...,333333,True,http://pbs.twimg.com/profile_images/8319031312...,https://pbs.twimg.com/profile_images/831903131...,NaN,True,False,None,None,None
3,1011036470,1011036470,MJ #RM,SoulTheangel,lraq,None,ليس مهم ان اروق للاخرين بفكري وفعلي المهم ان ا...,none,False,False,...,333333,True,http://pbs.twimg.com/profile_images/1085510994...,https://pbs.twimg.com/profile_images/108551099...,https://pbs.twimg.com/profile_banners/10110364...,True,False,None,None,None
4,236791004,236791004,المستشار/سهى الصالح,suha_alsaleh,None,None,مستشار بالفتوى والتشريع -مجلس الوزراء,none,False,False,...,333333,True,http://pbs.twimg.com/profile_images/1310942319...,https://pbs.twimg.com/profile_images/131094231...,https://pbs.twimg.com/profile_banners/23679100...,True,False,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99993,898286247868854272,898286247868854272,عبدالله,haikii14,You know how I’m,https://tellonym.me/AlHaiki,🎩,none,False,False,...,333333,True,http://pbs.twimg.com/profile_images/1310176260...,https://pbs.twimg.com/profile_images/131017626...,https://pbs.twimg.com/profile_banners/89828624...,True,False,None,None,None
99994,183592710,183592710,Talia levin,talialin,Tel Aviv,http://m.maariv.co.il/Author/Talia-Levin,"עיתונאית ,מעריב סופהשבוע- journalist, Maariv, ...",none,False,True,...,362720,True,http://pbs.twimg.com/profile_images/1229360892...,https://pbs.twimg.com/profile_images/122936089...,https://pbs.twimg.com/profile_banners/18359271...,False,False,None,None,None
99995,2772234830,2772234830,خ ل ي ف ه ⧗ ا ل ش ح ي,5loxf,دُبَــيّ | Dubai,https://curiouscat.qa/5loxf,"Marvel Studios presents Scarlett Johansson, as...",none,False,False,...,333333,True,http://pbs.twimg.com/profile_images/1239387631...,https://pbs.twimg.com/profile_images/123938763...,https://pbs.twimg.com/profile_banners/27722348...,False,False,None,None,None
99996,1933822058,1933822058,🇸🇦Abdullah AL-Sowail 🇸🇦,bumqdad1991,None,None,حاصل على #بكالوريوس'لغة عربية'جامعة الملك سعود...,none,False,False,...,333333,True,http://pbs.twimg.com/profile_images/1310591036...,https://pbs.twimg.com/profile_images/131059103...,https://pbs.twimg.com/profile_banners/19338220...,True,False,None,None,None
99997,739343169976979456,739343169976979456,HASAN,H_2099_H,None,None,أكره أن أشمت بأحد ، ولكن يعجبني الزمان حين يدو...,none,False,False,...,333333,True,http://pbs.twimg.com/profile_images/1307694612...,https://pbs.twimg.com/profile_images/130769461...,https://pbs.twimg.com/profile_banners/73934316...,True,False,None,None,None

In [8]:
df = pd.concat([df[:], users[:]], axis=1)

In [9]:
entities = df['entities'].apply(pd.Series)
entities

,hashtags,urls,user_mentions,symbols,media
0,"[{'text': 'الشيخ_صباح_الأحمد_الصباح', 'indices...",[],[],[],NaN
1,"[{'text': 'الشيخ_صباح_الاحمد_الصباح', 'indices...",[],[],[],"[{'id': 1310954760749678597, 'id_str': '131095..."
2,[],"[{'url': 'https://t.co/JvwHH0jCVM', 'expanded_...",[],[],NaN
3,[],[],"[{'screen_name': 'Rokkaya89', 'name': '34 🏆♍ ر...",[],NaN
4,[],"[{'url': 'https://t.co/yY1hYKrWyx', 'expanded_...",[],[],NaN
...,...,...,...,...,...
99993,[],[],[],[],NaN
99994,[],[],"[{'screen_name': 'becktalia', 'name': 'talia b...",[],NaN
99995,[],[],"[{'screen_name': 'i7arth', 'name': 'Hareth ~',...",[],NaN
99996,[],"[{'url': 'https://t.co/q54vJp9xoY', 'expanded_...",[],[],NaN
99997,[],[],"[{'screen_name': 'maiconroque27', 'name': 'Mai...",[],"[{'id': 1311239974000394241, 'id_str': '131123..."

In [10]:
df = pd.concat([df[:], entities[:]], axis=1)
df

,created_at,id,id_str,text,source,truncated,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,...,user_default_profile,user_default_profile_image,user_following,user_follow_request_sent,user_notifications,hashtags,urls,user_mentions,symbols,media
0,Tue Sep 29 14:49:06 +0000 2020,1310954762666487810,1310954762666487810,راح العود اللي خالي من العذاريب \nاللي يمناه م...,"<a href=""http://twitter.com/download/iphone"" r...",False,NaN,None,NaN,None,...,True,False,None,None,None,"[{'text': 'الشيخ_صباح_الأحمد_الصباح', 'indices...",[],[],[],NaN
1,Tue Sep 29 14:49:07 +0000 2020,1310954767032766465,1310954767032766465,#الشيخ_صباح_الاحمد_الصباح https://t.co/nAF4xDL5a4,"<a href=""http://twitter.com/download/iphone"" r...",False,NaN,None,NaN,None,...,True,False,None,None,None,"[{'text': 'الشيخ_صباح_الاحمد_الصباح', 'indices...",[],[],[],"[{'id': 1310954760749678597, 'id_str': '131095..."
2,Tue Sep 29 14:49:07 +0000 2020,1310954768693628929,1310954768693628929,انا لله وأنا اليه راجعون ، نعزي انفسنا ونعزي ا...,"<a href=""http://twitter.com/download/iphone"" r...",True,NaN,None,NaN,None,...,True,False,None,None,None,[],"[{'url': 'https://t.co/JvwHH0jCVM', 'expanded_...",[],[],NaN
3,Tue Sep 29 14:49:08 +0000 2020,1310954769255731205,1310954769255731205,@Rokkaya89 عبالك تاتو رباني شبي حظي 😭,"<a href=""http://twitter.com/download/iphone"" r...",False,1.310955e+18,1310954638380761090,2.363014e+09,2363014047,...,True,False,None,None,None,[],[],"[{'screen_name': 'Rokkaya89', 'name': '34 🏆♍ ر...",[],NaN
4,Tue Sep 29 14:49:07 +0000 2020,1310954769196945413,1310954769196945413,"وها قد غابت شمس الكويت , \nاللهم أجرنا في مصيب...","<a href=""http://twitter.com/download/iphone"" r...",True,NaN,None,NaN,None,...,True,False,None,None,None,[],"[{'url': 'https://t.co/yY1hYKrWyx', 'expanded_...",[],[],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99993,Wed Sep 30 09:42:57 +0000 2020,1311240107593281536,1311240107593281536,كنت أتساءل \nلماذا يختار الموت أفضل من فينا؟ \...,"<a href=""http://twitter.com/download/iphone"" r...",False,NaN,None,NaN,None,...,True,False,None,None,None,[],[],[],[],NaN
99994,Wed Sep 30 09:42:58 +0000 2020,1311240108331470848,1311240108331470848,@becktalia הגזמת,"<a href=""http://twitter.com/download/iphone"" r...",False,1.311240e+18,1311239747797487617,2.701762e+09,2701761817,...,False,False,None,None,None,[],[],"[{'screen_name': 'becktalia', 'name': 'talia b...",[],NaN
99995,Wed Sep 30 09:42:58 +0000 2020,1311240111024148481,1311240111024148481,@i7arth @LxRY_7 @Count__Vampire مسكين خلود ساك...,"<a href=""http://twitter.com/download/iphone"" r...",False,1.311240e+18,1311239939934351360,1.082444e+09,1082444168,...,False,False,None,None,None,[],[],"[{'screen_name': 'i7arth', 'name': 'Hareth ~',...",[],NaN
99996,Wed Sep 30 09:42:59 +0000 2020,1311240113389789184,1311240113389789184,من الطبيعي أن نختلف ونعتذر .. \nونعاتب .. \nو...,"<a href=""http://tapbots.com/tweetbot"" rel=""nof...",True,NaN,None,NaN,None,...,True,False,None,None,None,[],"[{'url': 'https://t.co/q54vJp9xoY', 'expanded_...",[],[],NaN
99997,Wed Sep 30 09:43:00 +0000 2020,1311240116271222785,1311240116271222785,@maiconroque27 💪🏻 https://t.co/23MmIpb7R2,"<a href=""http://twitter.com/download/iphone"" r...",False,NaN,None,4.144883e+09,4144883333,...,True,False,None,None,None,[],[],"[{'screen_name': 'maiconroque27', 'name': 'Mai...",[],"[{'id': 1311239974000394241, 'id_str': '131123..."

In [12]:
df.describe()

,id,in_reply_to_status_id,in_reply_to_user_id,quote_count,reply_count,retweet_count,favorite_count,quoted_status_id,user_id,user_followers_count,user_friends_count,user_listed_count,user_favourites_count,user_statuses_count
count,9.999800e+04,4.139800e+04,4.244600e+04,99998.0,99998.0,99998.0,99998.0,8.059000e+03,9.999800e+04,9.999800e+04,9.999800e+04,99998.00000,99998.000000,9.999800e+04
mean,1.311077e+18,1.309893e+18,5.988137e+17,0.0,0.0,0.0,0.0,1.307865e+18,5.115577e+17,4.520709e+03,9.551932e+02,8.52025,14203.524680,2.263636e+04
std,8.724601e+13,2.280536e+16,5.588499e+17,0.0,0.0,0.0,0.0,3.448818e+16,5.471012e+17,5.753909e+04,4.400316e+03,59.36276,45347.645056,6.261135e+04
min,1.310955e+18,2.501321e+09,1.148900e+04,0.0,0.0,0.0,0.0,2.564665e+17,8.061700e+05,0.000000e+00,0.000000e+00,0.00000,0.000000,1.000000e+00
25%,1.311002e+18,1.310971e+18,8.491756e+08,0.0,0.0,0.0,0.0,1.310926e+18,5.964789e+08,1.230000e+02,1.510000e+02,0.00000,365.000000,1.360000e+03
50%,1.311056e+18,1.311025e+18,7.980967e+17,0.0,0.0,0.0,0.0,1.310992e+18,4.006751e+09,4.440000e+02,3.750000e+02,0.00000,1877.000000,6.349000e+03
75%,1.311158e+18,1.311107e+18,1.161777e+18,0.0,0.0,0.0,0.0,1.311060e+18,1.087812e+18,1.416000e+03,8.727500e+02,3.00000,8782.000000,2.070300e+04
max,1.311240e+18,1.311240e+18,1.311214e+18,0.0,0.0,0.0,0.0,1.311239e+18,1.311222e+18,6.667396e+06,1.093351e+06,8172.00000,743434.000000,1.742455e+06

In [14]:
##save to csv
df.to_csv("data/output/sauditweets.csv")